Menu mobile
OsvaldoBC/portfolio-setup pull request #8
Opened 2022-09-06 20:18 UTC by OsvaldoBC

In this pull request, we add the portfolio mobile menu

2022-09-06 21:06 UTC, codepantha requested changes
# STATUS: REQUIRES CHANGES ♻️ 

## Hi team 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🎯 
✔️ Descriptive PR
✔️ No linter errors
✔️ Good commit history

## Required Changes ♻️
_Check the comments under the review._

- [ ] Since it's a collaborative project, kindly include your partner's details in the "Authors" section of the README 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-06 21:06 UTC, codepantha commented on css/styles.css
> +}
- [x] Kindly make the font weight of the mobile menu links to be `font-weight: 600` as specified in the Figma design to follow the specifications 👍 
- [x] Also take care to implement the margin between the links so they appear as specified in the design template
## Figma Design
![image](https://user-images.githubusercontent.com/46839548/188736805-85ee4ff1-a903-4812-93d0-9f3b0bdec3c2.png)

## Your Design
![image](https://user-images.githubusercontent.com/46839548/188736507-e0c59405-2e12-4db4-8bb7-ddfc5664314a.png)

2022-09-06 21:06 UTC, codepantha commented on css/styles.css
> +}
- [ ] Please let's follow the design guidelines and implement the blur on the mobile menu as shown in the template 🙏 
**HINT:** Use `backdrop-filter: blur(specify the blur in px)` 😎 
## Figma Design
![image](https://user-images.githubusercontent.com/46839548/188737545-ba29e04d-fb13-4fc1-8d80-dbcdcefa6f82.png)

## Your Design
![image](https://user-images.githubusercontent.com/46839548/188737436-41e24196-b4c4-4ca4-bf8d-42b4e28c32a2.png)

2022-09-07 03:34 UTC, Reem-lab approved these changes
# Hi Team,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯
<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>


## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the functionality✅
📌 Good commit messages ✅
📌 Professional README ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-07 03:35 UTC, merged